### ISSUE TITLE
Failing at Task[fedelemantuano.kibana : Debian - Ensure kibana-oss is installed ]

### ISSUE THREAD

**Issue by bouldrini** [fedelemantuano/ansible-kibana#5]
Hey fedelemantuano,

my playbook fails at 

`
TASK [fedelemantuano.kibana : Debian - Ensure kibana-oss is installed allow_unauthenticated={{ 'no' if es_apt_key else 'yes' }}, state=present, force={{ force_install }}, name={{ kibana_package_name }}{% if es_version is defined and es_version %}={{ es_version }}{% endif %}, cache_valid_time=86400]
`

Playbook looks like this

`
- hosts: kibana_servers
  become: yes
  tags: "installation"
  gather_facts: yes
  roles:
    - role: fedelemantuano.kibana

      kibana_config:
        server.name: "{{ inventory_hostname }}"
        server.port: 5601
        server.host: "0.0.0.0"
        elasticsearch.hosts: "http://{{ hostvars[inventory_hostname]['custom_elasticsearch_host_url'] }}:9200"

      kibana_install_oss: true
      kibana_data_dirs: "/var/lib/kibana"
      kibana_log_dir: "/var/log/kibana"
      kibana_restart_on_change: true
      kibana_start_service: true
      kibana_api_port: 5601
      kibana_api_host: 0.0.0.0
      es_version: "7.x"
      es_major_version: "7.x"
`

can you give me a hint ?

I'm under Ubuntu 16.04 xenial.

**Comment by bouldrini** [comment]
Oh, forgot the Logs:

`
task path: /home/bouldrini/elasticsearch_playbook/roles/fedelemantuano.kibana/tasks/kibana-Debian.yml:58
FAILED - RETRYING: Debian - Ensure kibana-oss is installed (5 retries left).
FAILED - RETRYING: Debian - Ensure kibana-oss is installed (4 retries left).
FAILED - RETRYING: Debian - Ensure kibana-oss is installed (3 retries left).
FAILED - RETRYING: Debian - Ensure kibana-oss is installed (2 retries left).
FAILED - RETRYING: Debian - Ensure kibana-oss is installed (1 retries left).

fatal: [kibana1]: FAILED! => {
"attempts": 5, 
"cache_update_time": 1567186495, 
"cache_updated": false,
"changed": false, 
"msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\" install 'kibana-oss=7.x'' failed: E: Version '7.x' for 'kibana-oss' was not found\n",
"rc": 100, 
"stderr": "E: Version '7.x' for 'kibana-oss' was not found\n", 
"stderr_lines": ["E: Version '7.x' for 'kibana-oss' was not found"], 
"stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n",
"stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information..."]
}
`

**Comment by bouldrini** [comment]
The mysterium might be aroung this line:
"stderr": "E: Version '7.x' for 'kibana-oss' was not found\n",

**Comment by fedelemantuano** [comment]
Yes from 7.x Elastic gives us x-pack for free. I can do a validation check before start the playbook.

**Comment by fedelemantuano** [comment]
Hi @bouldrini 

now we have this fail message:
```
TASK [kibana : fail when is selected kibana-oss for version 7.x msg=You can't install 'kibana-oss' for version 7.x of Elastic stack] *********************************************************************************************************************************************
fatal: [elasticsearch]: FAILED! => {"changed": false, "msg": "You can't install 'kibana-oss' for version 7.x of Elastic stack"}

```

**Comment by fedelemantuano** [comment]
I checked and now there are `oss` packages, for Debian and Red Hat so I will add them to this role.
